kind: Deployment # Deployment is kubernetes is a collection of Pd's
apiVersion: apps/v1
metadata:
  name: another-nginx-deployment
  namespce: default
spec:
  replicas: 5 # Number of replicas to deploy
  selector: # Gives Error if not use selector
    matchLabels:
      app: nginx
  templates:
    metadata:
      labels:
        app: nginx  
  spec:
    containers:
    - name: nginx-container
      image: nginx:latest # Docker image to use
